# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  database: toolfactor
  pool: 5
  timeout: 5000
  username: root
  password: root

test:
  adapter: mysql2
  database: toolfactor
  pool: 5
  timeout: 5000
  username: root
  password: root

production:
  adapter: mysql2
  database: toolfactor
  pool: 5
  timeout: 5000
  username: root
  password: root
